#!/usr/bin/env bash

cp /etc/hosts /etc/tmp && sed -i '$ s/$/ localhost.localdomain/' /etc/tmp && cp /etc/tmp /etc/hosts && rm /etc/tmp
sendmail -bd

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
